USE [master]
GO

/****** Object:  Database [QuanLyThuoc]    Script Date: 4/9/2024 2:14:09 PM ******/
CREATE DATABASE [QuanLyThuoc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyThuoc', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QuanLyThuoc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyThuoc_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QuanLyThuoc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyThuoc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyThuoc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QuanLyThuoc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyThuoc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyThuoc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QuanLyThuoc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyThuoc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QuanLyThuoc] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyThuoc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyThuoc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyThuoc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyThuoc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLyThuoc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyThuoc] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QuanLyThuoc] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLyThuoc] SET  READ_WRITE 
GO

